 #配置阿里巴巴连接池
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring-boot?characterEncoding=utf8
    username: root
    password: 12345678
    type: com.alibaba.druid.pool.DruidDataSource
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPr eparedStatements: true
    maxOpenPreparedStatements: 20

mybatis:
  type-aliases-package: com.chat.springboot.domain
  mapper-locations: classpath:/mapper/*.xml
  
mapper:
  mappers: com.user.springboot.mapper
  not-empty: false
  identity: MYSQL
  
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql